### ISSUE TITLE
exercises with answers

### ISSUE THREAD

**Issue by davidfarmer** [oscarlevin/discrete-book#19]
The MBX for exercises with answers seems good to me, but when I convert to HTML several things go wrong:

"ol" lists in the exercise do not look like lists

The answers appear visibly, in addition to being in a knowl

I have no experience debugging MBX (I just try to convert to the expected markup) so I am not
sure what to do in this case.  If the markup needs to be different, then I should be able to fix it.

**Comment by oscarlevin** [comment]
Are you talking about exercises in Homework sections?  Those are the ones where I have solutions (instead of answers) mixed in with the parts, instead of after all the parts.  Strangely enough, in your compiled version these get all jumbled up, but when I compiled it looked okay (perhaps Rob had fixed something between the two compilations?).  

In any event, having the answer after all the parts seems to work great, and this is what most of my book has.  In fact, I do not want solutions to the homework included in the book (those are hidden from students until I make them available after they have turned work in).  So the easy fix here is for me to just delete those solutions or move them to a private repository.

**Comment by davidfarmer** [comment]
It may be that my script fails to distinguish between "answer"
and "solution".  If those are genuinely different types of
objects, then they should be marked differently.

Also, several of us are about to deal with the issue of keeping
solutions private, so you should wait before doing anything by hand.

For now, please let me know if there a two different answer-like
objects in the LaTeX source, and let me know if the MBX for those
needs to be different.

**Comment by oscarlevin** [comment]
I think your script does exactly the right thing.  It converted by answers to answers and solutions to solutions.  I was using solutions in different contexts, sometimes to be displayed and other times to be hidden (outside of the "instructor edition").  So with the exception of figuring out how to eventually hide some solutions from students, I think we are good here.
