### ISSUE TITLE
Misc conversion bugs

### ISSUE THREAD

**Issue by oscarlevin** [oscarlevin/discrete-book#27]
Each of the following are small and I can fix on my own, but I'm including them in case you wan to polish the conversion script.

1. Text in \begin{center} \end{center} did not get put into a paragraph. (sec_logical-equiv.mbx, line 7).
2. \subsubsection*{...} did not get any treatment at all. (sec_binom.mbx).
3. \tikz{...} does not get any treatement (but \begin{tikz}...\end{tikz} does).
4. No idea why, but the end of sec_matchings.mbx puts \begin{questions} etc into paragraphs instead of converting. 

I'll add more as I find them.

**Comment by davidfarmer** [comment]
1. I removed the "center" from the LaTeX source.  Not sure what MBX markup
you will want.

2. SL2X does not allow subsubsection directly under a section (and I
don't think MBX does either).  So the source has to be modified, either
the LaTeX now or the MBX later.

3. Tikz will be one of the last things I fix.

4. Fixed.

1,2,4 fixed in next pull request.

**Comment by oscarlevin** [comment]
Great.  I'll take care of 2 on my own when I figure out how I want to structure that section.
