### ISSUE TITLE
Statements vs Predicates

### ISSUE THREAD

**Issue by skimmel** [oscarlevin/discrete-book#41]
There are times when "statement" is used, where it should be "predicate." In particular, when describing inductive proofs, you write "Let P(n) be the statement..." However P(n) is not a statement, since n is not fixed, so it should more precisely be "Let P(n) be the predicate..." Also, you use "predicate" in Exercise 0.2.9 without defining it until much later.

**Comment by oscarlevin** [comment]
Thanks for pointing this out (and sorry for not getting to this earlier).  I still need to think about what I want to do here.  I think "Let P(n) be the statement..." is pretty standard in mathematics, and if it is phrased, "For each n, let P(n) be the statement..." then there is no issue, since the variable is quantified.  I agree though that I should go back and make sure that the text is consistent.  And I'll look at 0.2.9 and rephrase.

**Comment by oscarlevin** [comment]
This issue was moved to oscarlevin/dmoi-instructor#6
