### ISSUE TITLE
CSS refactoring issues

### ISSUE THREAD

**Issue by davidfarmer** [oscarlevin/discrete-book#52]
The changes I am making to the main CSS files have had some bad consequences
for the HTML of your book.

I use this page as an example:
http://discrete.openmathbooks.org/dmoi/sec_polyfit.html

1.  The Greg's L (or at least the horizontal bottom segment) is visible in Investigate!s
and the left border and padding was messed up. (See ** below.)

2. The Solution's inside the .posterior of examples are not being styled properly.

3. Part of the L near those Solutions is appearing where it shouldn't.

4. The Permalinks are too close to the section titles (I think that is because in new HTML the
permalink is after, not inside the .heading. (See **)

5. In exercise 1 of 2.3 Exercises the Solution is too far down, but that is because
there is an empty "p".  Presumably that will go away when the HTML is rebuilt. (See **)

** In the following section, the Investigate styling is correct. It is not correct in Sec 2.3
because it is preceded by an empty "p", so the investigate is not the
first-child.  If you rebuild the HTML, then all the items with (See **) will change,
so I suggest rebuilding before fiddling with custom CSS.

And before adjusting custom CSS, I suggest letting me know any issues, in case
I can make the main CSS compatible with your customizations.  Also, I will continue
to overhaul the main CSS for at least the next week, so let's coordinate the work.
(Also, if you have a deadline substantially before the JMM, please let me know.)

**Comment by davidfarmer** [comment]
Would it be reasonable for you to repurpose "objectives" for your "Investigate!"s,
instead of having them as example-like, with the id starting with "investigate" being the
only clue that those are special?

**Comment by oscarlevin** [comment]
Thanks for the heads up.  I've rebuilt and published the results.  Most of the issues you described are fixed, except for *some* of the Investigates.  I'm not really sure why the Greg L's are showing up on some and not others.  

I do not want to repurpose "objectives", partly because adding objectives might happen at some point, but mostly because the Investigates are activities, not objectives.  I realize that the "styling by id part" is a hack, but until the html production gets smarter (like having the class be "example-like activity") I don't want to sacrifice semantics.

It would not be difficult to force my CSS overrides on all Investigates, but I can hold off on that for a bit if you like.  I don't think the book is in heavy use right now, but I would like it ready for the spring semester (which starts the week of JMM, at least here).

**Comment by davidfarmer** [comment]
In Section 3.3 there is an empty "p" before the Investigate!.
< p id="p-1415" >< /p >

That is caused by an error in either the source or the xslt.
We need to track that down, because empty "p" are always an error,
and they have unexpected consequences (such as the bad styling of that
Investigate!).

**Comment by davidfarmer** [comment]
I had suggested creating a generic environment, specifically so that it can be repurposed
without disturbing any of the "named" environments.  Maybe it is time to bring up that
discussion again?

**Comment by oscarlevin** [comment]
I need to go through and fix a bunch of things, apparently, including actually validating my source.  

On another front, I just noticed a change to some of the assemblage styles.  Right now,  "Permutatons on n elements" is styled correctly here: http://discrete.openmathbooks.org/dmoi/sec_counting-combperm.html, with the title sticking halfway out of the box.  On most other pages, this is now moved down inside the blue box (my custom margin-top: -1.25em is being overriden).

**Comment by davidfarmer** [comment]
Titles of assemblages should be okay now.

**Comment by oscarlevin** [comment]
Thanks, looks good.  

FYI, I've reverted back to my old build of the html since I wasn't able to quickly fix the numbering issues.  I have some family stuff for the next few hours, but I'll try to post an updated version on a test site later today, in case you want to check how your work affects mine.

**Comment by oscarlevin** [comment]
Fixed the numbering issue (thanks to Rob for finding the bug).  Thus the current live version is built using the latest mathbook pull.

**Comment by oscarlevin** [comment]
I've updated my custom css (mostly adding !important to lots of things, but also changing the borders to better match the print version).  It should be more robust to future changes.
