### ISSUE TITLE
Recent OS update corrupted fonts. Recompile?

### ISSUE THREAD

**Issue by kevcomedia** [oscarlevin/discrete-book#55]
Hi. After a recent update on my OS, the fonts don't get rendered properly anymore on several PDF viewers and in Chrome. I brought this up on their forum and they can confirm the corrupted fonts as well. One of the mods suggested a recompilation to see if it can fix the issue.

Here's a screenshot:
![image](https://user-images.githubusercontent.com/17902987/35312357-f865b26e-00f5-11e8-81e0-98d52e38a7b3.png)

**Comment by oscarlevin** [comment]
Thanks for this report.  Very strange.  I will try to recompile the document and send it to you to see if that helps (getting page breaks to agree with the print edition is a little tricky, so I would want to make sure the pdf version is working before I go through and do that).  

I'm not sure why recompiling would help, although I might be able to get the fonts to embed better (not sure why they are not).  Could you share some more info if you get a chance: what OS, what viewers work or don't, that sort of thing.  Also, a link to the forum you mentioned might help me track this bug down.

**Comment by kevcomedia** [comment]
I'm using Manjaro as my OS. Both of my PDF viewers don't work (evince and qpdfview). The fonts are also corrupted in Chromium but render properly on Firefox.

Here's the forum thread: https://forum.manjaro.org/t/38744

**Comment by davidfarmer** [comment]
That thread concerned PDF files from other sources.
Isn't it reasonable to guess that the problem is with the
Manjaro upgrade, and the specific problem with Oscars's book
will clear up at the same time as many other PDF files are fixed?

**Comment by kevcomedia** [comment]
I really suspect it's a problem with one of the updated packages (`freetype2` according to the last reply in that thread). I'm not sure if other PDFs were mentioned in that thread, but I went ahead and inspected all the other PDFs that I have and didn't find anything strange.

**Comment by oscarlevin** [comment]
I'm 90 percent certain there is nothing I can do on this end.  I checked, and all the fonts that are used in the pdf are embedded, so it is not as if you would need to specifically install fonts on your computer to read it.  For example, I can read the pdf on my smartphone or tablet, which definitely doesn't have the exotic fonts I use pre-installed.  In other words, I don't think that there is anything corrupted about the pdf itself, but rather some package on your machine that is reading information about the fonts in the pdf and using your own corrupted fonts to render them instead of the the embedded fonts from the pdf.  Maybe.

That said, I want to do everything possible to make the pdf accessible to everyone.  Could you try viewing the following versions and report back for each please?

- http://discrete.openmathbooks.org/pdfs/dmoi.pdf
- http://discrete.openmathbooks.org/pdfs/dmoi-tablet-dl1.pdf
- http://discrete.openmathbooks.org/pdfs/dmoi-selfprint.pdf

Thanks.

**Comment by kevcomedia** [comment]
I viewed each of them, and all versions have corrupted fonts :(

I visited the forum and found that a mod has found a fix. I tried it and the fonts now render properly.
