### ISSUE TITLE
discretebook-fall2015.pdf, page 53, exercise 5d

### ISSUE THREAD

**Issue by jonjitsu** [oscarlevin/discrete-book#6]
**Counting how many trapezoids can be made given the 2 rows of 7 dots.**

Perhaps it would help to add whether you consider a parallelogram as a trapezoid or not. Before attempting this exercise I checked a few resources and there seems to be 2 camps. One camp states that a trapezoid has exactly 1 set of parallel lines which would exclude parallelograms. The other camp states that a trapezoid has at least 1 set of parallel lines and that a parallelogram is a trapezoid. 

You could even make 2 questions out of it based on definition.

Anyways this is more of a sugesstion than an issue.

**Comment by oscarlevin** [comment]
Good point.  I never even considered the possibility of a parallelogram not being a trapezoid.  I've put a footnote in to this effect and added a part as you suggest.  I still need to go back and check the solution (perhaps there is a nicer way to think of this instead of just subtracting the parallelograms).
